id: 046513bc42834166ad31ef8f487103fa
initial_creation_type: ocr
source_metadata:
  volumes:
    1fad7fe7b3b14c838bdcbaba8ec781f7:
      base_file: v115.txt
      image_group_id: I1PD95961
      title: འཕགས་པ་ཀླུ་སྒྲུབ་ཀྱི་སྨོན་ལམ།
      total_pages: 1880
      volume_number: 116
